sudo: required

before_install:
  - wget -qO- https://binaries.cockroachdb.com/cockroach-v2.0.0.linux-amd64.tgz | tar  xvz
  - sudo cp -i cockroach-v2.0.0.linux-amd64/cockroach /usr/local/bin
  - ./start-cockroach.sh

language: java
jdk:
  - oraclejdk8
script: ./gradlew --info build
